objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmpInsertUpdateHandler.cls
public class EmpInsertUpdateHandler 
{
    public static void StatusUpdInsert(List<Employee__c> emp,Boolean Ins,Boolean Upd)
    {
        If(Ins==true)
                {
                    For(Employee__c eachemp : emp)
                   {
                    eachemp.Status__c='New Employee';
                   }
                }
    else if(Upd==true)
                {
                    For(Employee__c eachemp : emp)
                   {
                    eachemp.Status__c='Updated Employee';
                   }
                }
    }
}